/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalaCodeRouteImport } from './routes/sala.$code'
import { Route as ApiPublicLentesSfxRouteImport } from './routes/api/public/lentes-sfx'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaCodeRoute = SalaCodeRouteImport.update({
  id: '/sala/$code',
  path: '/sala/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLentesSfxRoute = ApiPublicLentesSfxRouteImport.update({
  id: '/api/public/lentes-sfx',
  path: '/api/public/lentes-sfx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sala/$code': typeof SalaCodeRoute
  '/api/public/lentes-sfx': typeof ApiPublicLentesSfxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sala/$code': typeof SalaCodeRoute
  '/api/public/lentes-sfx': typeof ApiPublicLentesSfxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sala/$code': typeof SalaCodeRoute
  '/api/public/lentes-sfx': typeof ApiPublicLentesSfxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/sala/$code'
    | '/api/public/lentes-sfx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/sala/$code'
    | '/api/public/lentes-sfx'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/sala/$code'
    | '/api/public/lentes-sfx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalaCodeRoute: typeof SalaCodeRoute
  ApiPublicLentesSfxRoute: typeof ApiPublicLentesSfxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sala/$code': {
      id: '/sala/$code'
      path: '/sala/$code'
      fullPath: '/sala/$code'
      preLoaderRoute: typeof SalaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lentes-sfx': {
      id: '/api/public/lentes-sfx'
      path: '/api/public/lentes-sfx'
      fullPath: '/api/public/lentes-sfx'
      preLoaderRoute: typeof ApiPublicLentesSfxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalaCodeRoute: SalaCodeRoute,
  ApiPublicLentesSfxRoute: ApiPublicLentesSfxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
